const actions: { [action: string]: string } = {
  LOGIN_WALLET: "LOGIN_WALLET",
  LOGOUT_WALLET: "LOGOUT_WALLET",
  SET_LOADING: "SET_LOADING",
  SET_THEME: "SET_THEME",
  CHANGE_NETWORK: "CHANGE_NETWORK",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
  REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
  SET_DID: "SET_DID",
  SET_TWITTER_VERIFIED: "SET_TWITTER_VERIFIED",
  SET_TWITTER_USERNAME: "SET_TWITTER_USERNAME",
};

export default actions;
